site_name: CannonKeys Documentation
theme:
  name: 'material'
  logo: 'images/white_transparent_256.png'
  favicon: 'images/logo.png'
repo_name: 'cannonkeys/ck-docs'
repo_url: 'https://github.com/cannonkeys/ck-docs'
markdown_extensions:
  - admonition
nav:
  - Home: index.md
  - Keyboard Kits:
    - Build Guide: bluepill-build.md
    - Testing your Bluepill: bluepill-test.md
    - Bluepill Modification: bluepill-mod.md
    - Flashing Guide: flashing.md
    - Firmware Guide: firmware.md
    - Default Layouts: default-layouts.md
    - Using Low Profile Sockets: sockets.md
    - Adding RGB Underglow: rgb_underglow.md
  - Instant60: instant60.md
  - AN-C: an_c.md
  - Satisfaction75:
    - Build Guide: satisfaction75/build_guide.md 
    - Flashing Guide: satisfaction75/flashing.md
    - User Guide: satisfaction75/user_guide.md
  - Chimera65:
    - Build Guide: chimera65/build_guide.md 
    - Flashing Guide: chimera65/flashing.md

extra:
  social:
    - type: 'github'
      link: 'https://github.com/cannonkeys'
    - type: 'instagram'
      link: 'https://www.instagram.com/cannon.keys/'
