site_name: CannonKeys Documentation
theme:
  name: 'material'
  logo: 'images/white_transparent_256.png'
  favicon: 'images/logo.png'
repo_name: 'cannonkeys/ck-docs'
repo_url: 'https://github.com/cannonkeys/ck-docs'
markdown_extensions:
  - admonition
nav:
  - Back to Cannonkeys: 'https://cannonkeys.com'
  - Docs Home: index.md
  - PCB Troubleshooting: troubleshooting.md
  - Bluepill Kits:
    - Build Guide: bluepill-build.md
    - Testing your Bluepill: bluepill-test.md
    - Bluepill Modification: bluepill-mod.md
    - Flashing Guide: flashing.md
    - Firmware Guide: firmware.md
    - Default Layouts: default-layouts.md
    - Using Low Profile Sockets: sockets.md
  - Stacked Kits:
    - Build Guide: stacked/stacked_build.md
    - BOMs: stacked/stacked_boms.md
  - Brutal Series Keyboards:
    - Build Guide: brutal/brutal_build.md
  - General HOWTOs:
    - PCB Basics: pcb_basics.md
    - Adding RGB Underglow: rgb_underglow.md
    - Removing PCB Rails: removing_pcb_rails.md
    - Raffle Queue: raffle-queue.md
    - VIA .json Loading: via-json-loading.md
  - Instant60: instant60.md
  - AN-C: an_c.md
  - Satisfaction75:
    - Build Guide: satisfaction75/build_guide.md 
    - Flashing Guide: satisfaction75/flashing.md
    - User Guide: satisfaction75/user_guide.md
  - Chimera65:
    - Build Guide: chimera65/build_guide.md 
    - Flashing Guide: chimera65/flashing.md
  - Bakeneko Build Guide: bakeneko.md
  - Resources: resources.md

extra:
  social:
    - type: 'github'
      link: 'https://github.com/cannonkeys'
    - type: 'instagram'
      link: 'https://www.instagram.com/cannon.keys/'
      
